Add support for banner and bannerAccentColor
Discord4J/discord-json pull request #103
Opened 2021-07-29 18:34 UTC by Azn9

Needed for https://github.com/Discord4J/Discord4J/issues/965

2021-08-02 04:42 UTC, quanticc requested changes

2021-08-02 04:42 UTC, quanticc commented on src/main/java/discord4j/discordjson/json/PartialUserData.java
> +    Possible<Optional<Integer>> bannerAccentColor();
Missing JsonProperty, and the method name should match discord's: accentColor

2021-08-19 02:32 UTC, darichey approved these changes

2021-08-20 02:49 UTC, quanticc approved these changes

2021-08-20 02:49 UTC, merged